### ISSUE TITLE
Request : QuickLook add pic link

### ISSUE THREAD

**Issue by Chamiu** [smittytone/PreviewMarkdown#2]
About Quick Link.
I hope to add a ability at \!\[img\]\(\).

**Comment by smittytone** [comment]
That feature is on my To Do list, but it may not be possible because of the way macOS’ preview system works, especially if the image is on an external server. I don't want to delay the preview, which is meant to be used as a quick check of a file's content, while the code waits for a large image to download.

**Comment by Chamiu** [comment]
Thanks for the explanation. I wait fix Apple.
